{
 "title": "SB8200 Modem Status",
 "time": { "from": "2021-11-01T04:00:00.000Z", "to": "2022-03-15T03:59:59.000Z" },
 "panels": [
  {
   "title": "Downstream Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "sb8200_channel_power{type=\"downstream\"}"
    }
   ]
  },
  {
   "title": "Downstream SNR/MER",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "sb8200_channel_snr{type=\"downstream\"}"
    }
   ]
  },
  {
   "title": "Downstream Corrected Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(sb8200_channel_corrected_total{type=\"downstream\"}[5m]))"
    }
   ]
  },
  {
   "title": "Downstream Uncorrectable Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(sb8200_channel_uncorrectable_total{type=\"downstream\"}[5m]))"
    }
   ]
  },
  {
   "title": "Upstream Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "sb8200_channel_power{type=\"upstream\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sb8200_uptime_seconds" }
   ]
  },
  {
   "title": "Channels with no signal lock",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (sb8200_channel_lock) - sum (sb8200_channel_lock)"
    }
   ]
  },
  {
   "title": "Downstream Per-Channel Signal Lock",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "sb8200_channel_lock{type=\"downstream\"}",
     "legendFormat": "{{channel_id}}"
    }
   ]
  },
  {
   "title": "Modem Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sb8200_connected" }
   ]
  },
  {
   "title": "Metric Scraper",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sb8200_up" }
   ]
  },
  {
   "title": "Downstream Channel Information",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sb8200_channel_info{type=\"downstream\"}"
    }
   ]
  },
  {
   "title": "Upstream Channel Information",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 25 },
   "targets": [
    {
     "expr": "sb8200_channel_info{type=\"upstream\"}"
    }
   ]
  },
  {
   "title": "Modem Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 31 },
   "targets": [
    { "expr": "sb8200_info" }
   ]
  }
 ]
}